### ISSUE TITLE
No code in the project!

### ISSUE THREAD

**Issue by julemand101** [fernan542/advent_of_code_2023#1]
There are no code to be found?!?!? THAT IS A MAJOR CRITICAL ISSUE AND HOW WHEN DO WE SEE CHRISTMAS EVER THIS YEAR TO BE FOUND!?!??!
![OIG](https://github.com/fernan542/advent_of_code_2023/assets/116227/01253f30-1e10-4eef-a8a1-98e621e38aee)

**Comment by fernan542** [comment]
Oh no, santa, sorry to disappoint you. I'll be pushing my code after office! 😂

**Comment by brainwo** [comment]
FlutterFlow is a great choice for making apps, no code programming should be a norm. Closing this issue as wontfix.

**Comment by fernan542** [comment]
I have some inner doubt with using FlutterFlow. You can't use power productivity tools there like GetX.

I'll follow you @brainwo wherever you go

**Comment by julemand101** [comment]
Code seems to have been added so I consider this satisfied solved!
![OIG](https://github.com/fernan542/advent_of_code_2023/assets/116227/90f4a5e6-0036-4147-94b3-cd228e228963)

**Comment by fernan542** [comment]
Hey julemand, I'll beat you in the leaderboard soon!

**Comment by julemand101** [comment]
> Hey julemand, I'll beat you in the leaderboard soon!

Should be very easy since I am not spending time on the tasks right now. Maybe start looking more into them in the upcoming weekend. :)

**Comment by brainwo** [comment]
![image](https://github.com/fernan542/advent_of_code_2023/assets/45139213/d143f796-774c-4202-927b-2819488263ca)
